# Generated by Django 4.2.21 on 2025-05-12 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.FloatField(help_text='Quantity (liters/kg)')),
                ('stock', models.FloatField(help_text='Quantity in Stock (liters/kg)')),
                ('sold', models.FloatField(help_text='Quantity Sold (liters/kg)')),
                ('production_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('min_stock', models.FloatField(help_text='Minimum Stock Threshold (liters/kg)')),
                ('reorder_qty', models.FloatField(help_text='Reorder Quantity (liters/kg)')),
                ('abc_class', models.CharField(blank=True, max_length=20)),
                ('stock_urgency', models.CharField(blank=True, max_length=20)),
                ('prediction', models.BooleanField(default=False)),
                ('confidence', models.FloatField(null=True)),
                ('last_predicted', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('predicted_sales', models.FloatField()),
                ('recommendation', models.TextField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.product')),
            ],
        ),
    ]
